version: '3.1'

services:
  collect:
    image: huanttok/article-as-code:latest
    volumes:
      - ./articles:/app/articles
    command:
      - collect
      - --username="$DEVTO_USERNAME"
      - --article-folder=/app/articles

#  sync-to-hashnode:
#    image: huanttok/article-as-code:latest
#    volumes:
#      - ./articles:/app/articles
#    command:
#      - sync
#      - --username="$HASHNODE_USERNAME"
#      - --destination=hashnode.dev
#      - --auth-token="$HASHNODE_AUTH_CODE"
#      - --article-folder=/app/articles
#    depends_on:
#      - collect

  sync-to-devto:
    image: huanttok/article-as-code:latest
    volumes:
      - ./articles:/app/articles
    command:
      - sync
      - --username="$DEVTO_USERNAME"
      - --destination=dev.to
      - --auth-token="$DEVTO_AUTH_CODE"
      - --article-folder=/app/articles
    depends_on:
      - collect

  update-article-list:
    image: huanttok/article-listing:latest
    volumes:
      - ./templates:/app/templates
    command:
      - --limit=5
      - --username="$DEVTO_USERNAME"
      - --template-file=templates/README.md.tpl
      - --out-file=templates/README.md
secrets:
  auth:
    file: ./.secrets.txt
